[workspace]
members = [
  "collection-manager",
  "collection-manager/meta",
  "nft-minter",
  "nft-minter/meta",
  "royalties-handler",
  "royalties-handler/meta",
  "esdt-system-sc-mock",
  "esdt-system-sc-mock/meta"
]
