[package]
name = "collection-manager-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "Dorin Marian Iancu, dorin.iancu@elrond.com" ]

[dev-dependencies]

[dependencies.collection-manager]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.30.0"
